config/routes.rb
require 'api_version'

Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/about'

  get 'explore', to: 'explore#map'
  # get 'explore/map'

  devise_for :users
  resources :sports
  resources :venues

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: APIVersion.new('v1', true) do
      resources :venues, only: [:index, :show]
      resources :sports, only: [:index, :show]
    end
  end
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_and_belongs_to_many :venues
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ActiveRecord::Base

  has_and_belongs_to_many :sports

  geocoded_by :full_address
  after_validation :geocode, :if => :full_address_changed?

  # validations

  validates :name, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :sports, presence: true

  def self.sports_in(ids)
    if ids.blank?
      includes(:sports).all
    else
      includes(:sports).where(sports: { id: ids })
    end
  end

  def self.in_bounds(bounds)
    where(
      latitude:  bounds.bottom..bounds.top,
      longitude: bounds.left..bounds.right
    )
  end

  def full_address
    "#{self.city} #{self.address}"
  end

  def full_address_changed?
    city_changed? || address_changed?
  end
end

app/controllers/api/v1/sports_controller.rb
module Api::V1
  class SportsController < ApplicationController
    before_action :set_sport, only: [:show]

    # GET /sports
    def index
      @sports = Sport.all
    end

    # GET /sports/1
    def show
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_sport
        @sport = Sport.find(params[:id])
      end
  end
end

app/controllers/api/v1/venues_controller.rb
module Api::V1
  class VenuesController < ApplicationController
    def index
      @location = GeolocationService.new(params[:location]).location
      venues = VenueFilter.new(@location, params).venues
      @venues_json = VenuePresenter.wrap(venues).map(&:to_json)

      render json: {
        location: @location.to_hash,
        venues: @venues_json
      }
    end

    def show
      venue = Venue.includes(:sports).find(params[:id])
      @venue_json = VenuePresenter.new(venue).to_json

      render json: @venue_json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def index
    @venues = Venue.all
  end

  def map
    @location = GeolocationService.new(params[:location]).location
    @venues = VenueFilter.new(@location, params).venues

    @venues_json = VenuePresenter.wrap(@venues).map(&:to_json).to_json # Last one converts from Ruby Hash to JSON string
    @sports = Sport.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  before_action :set_sport, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :edit, :create, :update, :destroy]

  # GET /sports
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  def create
    @sport = Sport.new(sport_params)

    if @sport.save
      redirect_to @sport, notice: 'Sport was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sports/1
  def update
    if @sport.update(sport_params)
      redirect_to @sport, notice: 'Sport was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sports/1
  def destroy
    @sport.destroy
    redirect_to sports_url, notice: 'Sport was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name, :description)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /venues
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to "/explore", notice: 'Venue was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /venues/1
  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /venues/1
  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :description, :city, :address, :phone, :email, :url_website, :url_facebook, :other_info, :status, :sport_ids => [])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/google_maps_helper.rb
module GoogleMapsHelper
  def google_maps_api_key
    #TODO move this in some config file
    #don-t use this key in your own project, it only works for domain http://sportzone.herokuapp.com
    'AIzaSyBi-pdTqdVRjcTGQlKYcO06DrnT-QSmjSM'
  end

  def google_maps_root_url
    'http://maps.googleapis.com/maps/api/js'
  end

  def google_maps_api_url
    "#{google_maps_root_url}?key=#{google_maps_api_key}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/explore/_venue.html.erb
<div class="sport-venue">
    <p class="city"><%= venue.city %></p>
    <p class="lead" style="margin-bottom:2px"><%= link_to venue.name, venue %></p>
    <p><i class="glyphicon glyphicon-map-marker"></i> <%= venue.address %></p>
    <% #= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{venue.latitude}%2C#{venue.longitude}" %>
    <% venue.sports.each do |venue| %>
    <label class="label-sport"><%= venue.name %></label>
    <% end %>
    <div class="js-venue-other-info other-info hidden">
        <p><strong>Alte informatii</strong></p>
        <p><%= venue.description %></p>
        <p><i class="glyphicon glyphicon-phone"></i> <%= venue.phone %></p>
        <p><i class="glyphicon glyphicon-globe"></i><%= venue.url_website %></p>
        <p><%= venue.url_facebook %></p>
    </div>
    <a class="view-more js-view-more"><i class="glyphicon glyphicon-menu-down"></i></a>
</div>

app/views/explore/index.html.erb
<h1>Explore </h1>
<hr/>
<div class="row">
<% @venues.each do |venue| %>
      <div class="col-md-4">
    <%= render "venue", venue: venue  %>
      </div>
<% end %>
</div>

app/views/explore/map.html.erb
<script type="text/javascript">
  $(function() {
    // Loading Bootstrapped Models
    var venues = new Sportzone.Collections.Venues;
    venues.reset(<%= raw @venues_json %>);
    var sports = new Sportzone.Collections.Sports;
    sports.reset(<%= raw @sports.to_json %>);
    var location = new Sportzone.Models.Location({
      search_string: '<%= @location.search_string %>',
      latitude: <%= @location.latitude %>,
      longitude: <%= @location.longitude %>,
      top: <%= @location.top %>,
      right: <%= @location.right %>,
      bottom: <%= @location.bottom %>,
      left: <%= @location.left %>
    });

    window.mapPageView = new Sportzone.Views.MapPage({
        venues: venues,
        sports: sports,
        location: location,
        iconURL: '<%= asset_url("marker-pin-full.png")%>'
    }).render();
  });
</script>

<div class="col-md-4" style="height:100%;">
    <div id="side-menu">
        <div class="panel-content">
          <div class="panel-content-inner">
            <div id="search-form" class="panel panel-default clearfix" style="padding:10px">
              <%= form_tag api_venues_path, method: "get", remote: true, class: "inline-form" do %>
                  <div class="form-group">
                    <%= text_field_tag :location, nil, class: "form-control", placeholder: "Search city", value: @location.search_string %>
                  </div>
                  <div class="form-group">
                    <%= select_tag :query, options_from_collection_for_select(@sports, "id", "name"), multiple: true, class: 'form-control chosen-select', style: "width:100%" %>
                  </div>
                  <%= submit_tag "Search", class:"btn btn-primary btn-block" %>
              <% end %>

            </div>
            <h2>Locatii</h2>
            <div id="venues-list"></div>
          </div>
        </div>
    </div>
</div>
<div class="col-md-8" style="height:100%;">
    <div id="map-container">
        <div id="map"></div>
    </div>
</div>

app/views/home/about.html.erb
<div id="home-background">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="home-page">
        <h1>Despre SportZone</h1>
        <p class="lead">Find location-based venues for sports and sports activities.</p>
        <div id = "about-project" style="font-size:1.2em;padding-top: 40px">


          <p>SportZone te ajuta sa faci miscare in locul potrivit!</p>

          <p>SportZone este un tool pentru crearea mult mai facila a diferite tipuri de aplicatii software care integreaza informatii despre activitatile sportive si de agrement.</p>

          <p>Aplicatia se prezinta sub forma unei harti interactive care pune la dispozitia utilizatorului toate locatiile unde poate desfasura activitati sportive si de agrement precum:
          Fitness, Baschet, Fotbal, Tenis de masa, Volei, Adventure Park, Atletism, Airsoft, Badminton, Biliard, Bowling, Ciclism, Dans, Darts, Echitatie, Fotbal, Golf, Hamace, Handbal, Inot,Judo, Karate, Alpinism, Patinaj, Sporturi de iarna, Arte martiale, Motociclism, Paintball, Tenis, Squash. </p>

          <p>Un plus valoare al acestei aplicatii este conferit de utilitatea Open Source. Ceea ce presupune ca platforma este populata cu informatii despre locatii, dar se ofera oricui posibilitatea de a adauga unele noi, ceea ce asigura crestea continua a volumului de date disponibil.</p>

          <p>Aceasta aplicatie a fost dezvoltata in cadrul Open Data Hackathon, Cluj-Napoca 2015, de catre <a href="https://twitter.com/rosucristi" target="_blank">Rosu Cristian</a>, <a href="https://github.com/tudorpavel" target="_blank">Pavel Tudor</a>  si colaboratorii <a href="https://www.facebook.com/catrinel.lupu" target="_blank">Lupu Catrinel</a>, <a href="" target="_blank" >Lupu Madalina</a>, <a href="https://www.facebook.com/grecu.victor" target="_blank">Grecu Ioan Victor</a> si <a href="https://www.facebook.com/timis.daniel.3" target="_blank">Timis Daniel</a> </p>
          <p>Codul sursa si aplicatia rezultata sunt disponibile sub licenta libera, pe platforma <a style="color:white;text-decoration:underline" href="https://github.com/cristianrosu/sportzone" target="_blank">Github</a></p>


          <ul id="home-menu">
            <li><%= link_to "Map Explore", explore_path %></li>
            <li><%= link_to "About", home_about_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home-background">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="home-page">
          <h1>SportZone</h1>
          <p class="lead">Find location-based venues for sports and sports activities.</p>
          <div style="padding-top: 40px">

              <%= form_tag(explore_path, method: "get", class: "form-inline") do %>
                  <div class="form-group">
                      <%= text_field_tag :location, nil, class: "form-control input-lg", value: "Cluj Napoca", placeholder: "Search city" %>
                      <%= submit_tag "Search", class: "btn btn-primary btn-lg" %>
                  </div>
              <% end %>

              <ul id="home-menu">
                <li><%= link_to "Map Explore", explore_path %></li>
                <li><%= link_to "About", home_about_path %></li>
              </ul>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SPORTZONE', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <!--<ul class="nav navbar-nav">-->
        <% # = render 'layouts/navigation_links' %>
      <!--</ul>-->
      <%= link_to "Adauga Locatie", new_venue_path, class: "btn btn-success navbar-btn pull-right" %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sportzone" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sportzone" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag google_maps_api_url %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/sports/_form.html.erb
<%= simple_form_for(@sport) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<div class="container clearfix">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
          <h1>Toate Sporturile </h1>
            <% if user_signed_in? %>
            <%= link_to '+ New Sport', new_sport_path ,class:"btn btn-success" %>
            <% end %>
          <hr/>
          <% @sports.each do |sport| %>
            <p class="lead"><%= sport.name %></p>
            <% if user_signed_in? %>
              <span><%= link_to 'Show', sport %></span>,
              <span><%= link_to 'Edit', edit_sport_path(sport) %></span>,
              <span><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></span></p>
            <% end %>
          <% end %>
    </div>
  </div>
</div>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sport.description %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>

app/views/venues/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :city %>
    <%= f.input :address %>

    <%= f.association :sports, collection: Sport.all, include_blank: true, input_html: { class: "chosen-select" } %>

    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :url_website %>
    <%= f.input :url_facebook %>
    <% # = f.input :other_info %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit location</h1>
    <hr/>
    <%= render 'form' %>
  </div>
</div>


<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <h1 style="text-align:center">Adauga o locatie</h1>
        <hr/>
        <%= render 'form' %>
    </div>
</div>

app/views/venues/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default clearfix"  style="margin-top: 80px; padding:2em">
        <div class="pull-right">
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@venue.latitude}%2C#{@venue.longitude}" %>
        </div>
        <div class="pull-left">
            <h1><%= @venue.name %></h1>
            <p class="lead" style="margin-bottom:10px;"><i class="glyphicon glyphicon-map-marker"></i> <%= @venue.city %>,  <%= @venue.address %> </p>
            <% @venue.sports.each_with_index do |sport| %>
              <span class="label label-primary"><%= sport.name %></span>
            <% end %>
            <hr/>

            <h4>Alte Informatii:</h4>
            <p> <strong>Telefon:</strong>  <%= @venue.phone %> </p>

            <p> <strong>Email:</strong>  <%= @venue.email %> </p>

            <p> <strong>website:</strong> <%= @venue.url_website %> </p>

            <p> <strong>facebook:</strong> <%= @venue.url_facebook %>  </p>
        </div>
      </div>
      <div class="panel panel-default clearfix" style="padding:2em">
        <p> <strong>Despre:</strong> <%= @venue.description %> </p>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>